view: marts_orders {
  sql_table_name: `thc-challenge.sales_recruitment_marts.marts_orders` ;;

  drill_fields: [
    order_id,
    order_date,
    customer_id,
    net_sales,
    qty_product
  ]

  dimension: order_id {
    primary_key: yes
    type: number
    value_format_name: id
    group_label: "1.1 Identifiers"
    label: "Order ID"
    description: "Unique ID of the order."
    sql: ${TABLE}.order_id ;;
  }

  dimension: customer_id {
    type: number
    value_format_name: id
    group_label: "1.1 Identifiers"
    label: "Customer ID"
    description: "ID of the customer who placed the order."
    sql: ${TABLE}.customer_id ;;
  }

  dimension_group: order {
    type: time
    timeframes: [date, day_of_week, week, month, quarter, year]
    convert_tz: no
    datatype: date
    group_label: "1.2 Order date"
    label: "Order"
    description: "Date the order was placed."
    sql: ${TABLE}.order_date ;;
  }

  dimension: net_sales {
    type: number
    hidden: yes
    sql: ${TABLE}.net_sales ;;
  }

  dimension: qty_product {
    type: number
    hidden: yes
    sql: ${TABLE}.qty_product ;;
  }

  dimension: products {
    hidden: yes
    sql: ${TABLE}.products ;;
  }

  measure: order_count {
    type: count
    group_label: "1.3 Order activity"
    label: "Orders"
    description: "Number of orders placed during the selected period."
  }

  measure: customer_count {
    type: count_distinct
    sql: ${customer_id} ;;
    group_label: "1.3 Order activity"
    label: "Customers"
    description: "Number of customers who placed at least one order."
  }

  measure: orders_per_customer {
    type: number
    sql: SAFE_DIVIDE(${order_count}, ${customer_count}) ;;
    value_format_name: decimal_2
    group_label: "1.3 Order activity"
    label: "Orders per customer"
    description: "Average number of orders per customer."
  }

  measure: total_net_sales {
    type: sum
    sql: ${net_sales} ;;
    value_format: "#,##0.00"
    group_label: "1.4 Sales performance"
    label: "Total net sales"
    description: "Total order value, excluding taxes. Currency is defined by the source data."
  }

  measure: average_order_value {
    type: number
    sql: SAFE_DIVIDE(${total_net_sales}, ${order_count}) ;;
    value_format: "#,##0.00"
    group_label: "1.4 Sales performance"
    label: "Average order value"
    description: "Net sales divided by the number of orders."
  }

  measure: total_units {
    type: sum
    sql: ${qty_product} ;;
    value_format_name: decimal_0
    group_label: "1.5 Basket performance"
    label: "Total units"
    description: "Total number of units sold."
  }

  measure: average_units_per_order {
    type: number
    sql: SAFE_DIVIDE(${total_units}, ${order_count}) ;;
    value_format_name: decimal_2
    group_label: "1.5 Basket performance"
    label: "Units per order"
    description: "Average number of units included in one order."
  }
}

view: marts_orders__products {
  dimension: order_product_key {
    primary_key: yes
    hidden: yes
    type: string
    sql:
      CONCAT(
        CAST(${marts_orders.order_id} AS STRING),
        '-',
        CAST(${product_id} AS STRING)
      ) ;;
  }

  dimension: product_id {
    type: number
    value_format_name: id
    group_label: "3.1 Product details"
    label: "Product ID"
    description: "ID of the product sold."
    sql: product_id ;;
  }

  dimension: quantity {
    type: number
    hidden: yes
    sql: quantity ;;
  }

  dimension: total_product_sales {
    type: number
    hidden: yes
    sql: total_product_sales ;;
  }

  measure: product_units {
    type: sum
    sql: ${quantity} ;;
    value_format_name: decimal_0
    group_label: "3.2 Product performance"
    label: "Product units"
    description: "Number of units sold."
  }

  measure: product_net_sales {
    type: sum
    sql: ${total_product_sales} ;;
    value_format: "#,##0.00"
    group_label: "3.2 Product performance"
    label: "Product net sales"
    description: "Net sales generated by the product, excluding taxes."
  }

  measure: product_count {
    type: count_distinct
    sql: ${product_id} ;;
    group_label: "3.2 Product performance"
    label: "Unique products sold"
    description: "Number of different products sold."
  }

  measure: product_order_count {
    type: count_distinct
    sql: ${marts_orders.order_id} ;;
    group_label: "3.2 Product performance"
    label: "Orders containing the product"
    description: "Number of orders containing the product."
  }
}
